# Generated by Django 5.0.6 on 2025-11-13 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("rent_roll", "Rent Roll"), ("flyer", "Flyer")],
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("pages", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="FieldCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=64)),
                ("record_id", models.IntegerField()),
                ("field_name", models.CharField(max_length=64)),
                ("page", models.IntegerField()),
                ("x0", models.FloatField()),
                ("y0", models.FloatField()),
                ("x1", models.FloatField()),
                ("y1", models.FloatField()),
                ("snippet", models.CharField(blank=True, max_length=500)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="core.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=128)),
                ("state", models.CharField(blank=True, max_length=64)),
                ("zipcode", models.CharField(blank=True, max_length=20)),
                ("year_built", models.CharField(blank=True, max_length=32)),
                ("sqft", models.IntegerField(blank=True, null=True)),
                ("unit_count", models.IntegerField(blank=True, null=True)),
                ("cap_rate", models.FloatField(blank=True, null=True)),
                (
                    "source_document",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="properties",
                        to="core.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.IntegerField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("text", models.TextField(blank=True)),
                ("bbox_x0", models.FloatField(default=0)),
                ("bbox_y0", models.FloatField(default=0)),
                ("bbox_x1", models.FloatField(default=0)),
                ("bbox_y1", models.FloatField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_number", models.CharField(blank=True, max_length=64)),
                ("beds", models.CharField(blank=True, max_length=16)),
                ("baths", models.CharField(blank=True, max_length=16)),
                ("sqft", models.IntegerField(blank=True, null=True)),
                ("rent", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=64)),
                ("lease_start", models.CharField(blank=True, max_length=64)),
                ("lease_end", models.CharField(blank=True, max_length=64)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="core.property",
                    ),
                ),
            ],
        ),
    ]
