# Generated by Django 5.0.6 on 2025-11-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="unit_type",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
